services:
  nginx:
    image: nginx:1.25.5
    ports:
      - "80:80"
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
    restart: on-failure
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

volumes:
  postgres_data:

configs:
  nginx-config:
    file: ./nginx/nginx.conf
