services:
  nginx:
    image: nginx:1.25.5
    depends_on:
      - fastapi_app
    ports:
      - "80:80"
    volumes:
      - ./static:/home/web/default/static
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
    deploy:
      restart_policy:
        condition: on-failure
  
  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8  # Google Public DNS
      - 8.8.4.4  # Google Public DNS
  
  fastapi_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

volumes:
  postgres_data:

configs:
  nginx-config:
    file: ./nginx/nginx.conf
